gMACEDONIA_ID="53293"
MACEDONIA_BBOX="40.852478,20.4529023,42.3739044,23.034051"


import requests
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import json
import time
from claude import enrich_site, render_map
import math


def calculate_area(geometry):
    if not geometry or len(geometry) < 3:
        return 0

    # 1. Convert degrees to meters (approximate for Macedonia)
    # Using 41.6 as the average latitude for Bregalnica region
    lat_to_m = 111000
    lon_to_m = 111000 * math.cos(math.radians(41.6))

    nodes = []
    for pt in geometry:
        nodes.append((pt['lon'] * lon_to_m, pt['lat'] * lat_to_m))

    # 2. Shoelace Formula
    area = 0.0
    n = len(nodes)
    for i in range(n):
        j = (i + 1) % n
        area += nodes[i][0] * nodes[j][1]
        area -= nodes[j][0] * nodes[i][1]

    return abs(area) / 2.0

def box_to_poly_string(box_str):
    # box_str is "s,w,n,e"
    coords = box_str.split(',')
    s, w, n, e = coords[0], coords[1], coords[2], coords[3]

    # Create 4 corners:
    # Bottom-Left, Top-Left, Top-Right, Bottom-Right
    # (Note: Overpass connects the last back to the first automatically)
    p1 = f"{s} {w}"
    p2 = f"{n} {w}"
    p3 = f"{n} {e}"
    p4 = f"{s} {e}"

    return f"{p1} {p2} {p3} {p4}"

def get_buffer_squares(points, grid_size_km, buffer_km):
    # Roughly: 1 degree lat ≈ 111km.
    # (Note: Lon varies by latitude, but let's keep it simple for now)
    res = grid_size_km / 111.0
    buffer_cells = math.ceil(buffer_km / grid_size_km)

    covered_squares = set()

    for lon, lat in points:
        # Normalize coordinates to grid indices
        grid_x = math.floor(lon / res)
        grid_y = math.floor(lat / res)

        # Add the square and its neighbors within the buffer range
        for dx in range(-buffer_cells, buffer_cells + 1):
            for dy in range(-buffer_cells, buffer_cells + 1):
                covered_squares.add((grid_x + dx, grid_y + dy))

    return covered_squares

def get_overpass_bboxes(squares, res):
    # 1. Group x-coordinates by their y-row
    rows = {}
    for gx, gy in squares:
        rows.setdefault(gy, []).append(gx)

    merged_bboxes = []

    for gy, x_list in rows.items():
        x_list.sort()

        if not x_list: continue

        # 2. Find continuous segments in the row
        start_x = x_list[0]
        for i in range(len(x_list)):
            # If it's the last item or the next item isn't consecutive
            if i == len(x_list) - 1 or x_list[i + 1] != x_list[i] + 1:
                end_x = x_list[i]

                # Convert back to actual Lat/Lon
                # Overpass bbox format: (minLat, minLon, maxLat, maxLon)
                s, w = gy * res, start_x * res
                n, e = (gy + 1) * res, (end_x + 1) * res

                merged_bboxes.append(f"{s:.4f},{w:.4f},{n:.4f},{e:.4f}")
                start_x = x_list[i + 1] if i < len(x_list) - 1 else None

    return merged_bboxes

def factories_in_polygon2(polygon_string):
    # Ensure polygon_string is "lat lon lat lon" without commas
    #clean_poly = polygon_string.replace(",", " ")
    #print("clean_poly",clean_poly)

    # return """
    # [out:json][timeout:300];
    # (
    #
    #   nw["man_made"="works"](poly:"41.8919 22.2072 41.9369 22.2072 41.9369 22.8829 41.8919 22.8829");
    #   nw["product"](poly:"41.8919 22.2072 41.9369 22.2072 41.9369 22.8829 41.8919 22.8829");
    #   nw["building"="industrial"](poly:"41.8919 22.2072 41.9369 22.2072 41.9369 22.8829 41.8919 22.8829");
    # );
    #
    # out geom;
    #
    # """



    # #nw["landuse"~"farmland|farmyard"](poly:"{polygon_string}");
    #
    #   nw["agriculture"](poly:"{polygon_string}");
    #   nw["building"~"barn|stable|silo|greenhouse"](poly:"{polygon_string}");
    #
    #
    #
    return f"""
    [out:json][timeout:300];
    (
      
      nw["man_made"="works"](poly:"{polygon_string}");
      nw["product"](poly:"{polygon_string}");
      nw["building"="industrial"](poly:"{polygon_string}");    
     
      nw["industrial"="agriculture"](poly:"{polygon_string}");
      
      
    );
    out geom;
    """

overpass_url = "https://overpass.kumi.systems/api/interpreter"

overpass_query_vardar=f"""
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“waterway=river and name=Vardar and type:way”
*/
[out:json][timeout:300][bbox:{MACEDONIA_BBOX}];
// gather results
way["waterway"="river"]["name"="Брегалница"];
// print results
out geom;"""



response = requests.post(overpass_url, data={'data': overpass_query_vardar})


data = response.json()

abbr_points=[]
for element in data.get('elements', []):
    points = element.get('geometry', [])


    i=0
    for i, point in enumerate(points):
        i+=0
        lat = point['lat']
        lon = point['lon']
        point_tmp=(lon,lat)
        #print(f"Point {i}: Lat {lat}, Lon {lon}")
        if i%100==0:
            abbr_points.append(point_tmp)

#for getting bounds

squares=get_buffer_squares(abbr_points,5.0,5.0)
print(squares)


grid_size_km = 5.0
res = grid_size_km / 111.0

optimized_boxes = get_overpass_bboxes(squares, res)
#print(f"Original squares: {len(squares)}")
#print(f"Optimized boxes for Overpass: {len(optimized_boxes)}")
k=0

all_results = []

for box in optimized_boxes:

    s, w, n, e = map(float, box.split(','))
    grid_square_data = {
        "square_id": k,
        "bounds": {
            "min_lat": s, "min_lon": w,
            "max_lat": n, "max_lon": e
        },
        "sites": []
    }

    print(box)
    poly_coor=box_to_poly_string(box)
    query=factories_in_polygon2(poly_coor)

    max_retries = 3
    retry_delay = 5  # Seconds to wait after first failure
    success = False
    data = {}

    for attempt in range(max_retries):
        try:
            print(f"Checking Box {k} (Attempt {attempt + 1})...")
            response_industry = requests.post(overpass_url, data={'data': query}, timeout=310)

            # If the server says "429 Too Many Requests" or "504 Timeout"
            if response_industry.status_code != 200:
                print(f"Server returned status {response_industry.status_code}. Retrying in {retry_delay}s...")
                time.sleep(retry_delay)
                retry_delay *= 2  # Wait longer each time (5s, 10s, 20s)
                continue

            data = response_industry.json()
            success = True
            break  # Exit the retry loop

        except (requests.exceptions.RequestException, json.JSONDecodeError) as e:
            print(f"Connection error: {e}. Retrying...")
            time.sleep(retry_delay)
            retry_delay *= 2

    if not success:
        print(f"!! Failed to fetch Box {k} after {max_retries} attempts. Skipping.")
        continue

    print(query)
    #data = response_industry.json()
    k+=1
    print("box: ",k)
    #print(json.dumps(data, indent=4))

    for element in data.get('elements', []):
        # 1. Get the name (fall back to "Unnamed" if the tag doesn't exist)
        tags = element.get('tags', {})
        name = tags.get('name', tags.get('man_made', 'Industrial Site'))

        # 2. Get coordinates
        # Case A: It's a Node (single point)
        # --- DIFFERENTIATION LOGIC ---
        category = "Unknown"

        # 1. Check for Agriculture
        # if any(key in tags for key in ['agriculture', 'farming']):
        #     category = "Agriculture"
        # elif tags.get('landuse') in ['farmland', 'farmyard', 'allotments', 'orchard', 'vineyard']:
        #     category = "Agriculture"
        # elif tags.get('building') in ['barn', 'stable', 'silo', 'greenhouse']:
        #     category = "Agriculture"

        # 2. Check for Industry
        if any(key in tags for key in ['man_made', 'product', 'industrial']):
            category = "Industry"
        elif tags.get('building') == 'industrial' or tags.get('landuse') == 'industrial':
            category = "Industry"

        product = tags.get('product')  # Common for industry
        crop = tags.get('crop')  # Common for farmland
        agri_type = tags.get('agriculture')  # Specific agri-type (e.g., rice, poultry)

        # Combine them into one "Detail" string for easy printing
        specific_info = product or crop or agri_type or "Unknown"


        # --- GET NAME & FEATURE DETAIL ---
        # Get the specific detail (e.g., 'barn' or 'works')
        feature_detail = tags.get('landuse', tags.get('building', tags.get('man_made', 'site')))
        name = tags.get('name', f"Unnamed {feature_detail}")

        area = 0

        if element['type'] == 'node':
            lat = element['lat']
            lon = element['lon']

        # Case B: It's a Way (a building outline)
        elif element['type'] == 'way':
            # We'll take the center (centroid) of the building for the label
            geometry = element.get('geometry', [])
            area=calculate_area(geometry)

            if geometry:
                lat = sum(p['lat'] for p in geometry) / len(geometry)
                lon = sum(p['lon'] for p in geometry) / len(geometry)
        site_obj = {
            "name": name,
            "category": category,
            "type": feature_detail,
            "specifics": specific_info,
            "lat": round(lat, 6),
            "lon": round(lon, 6),
            "area_m2": round(area, 2),
            "osm_id": element['id']
        }

        if  "Unknown" not in name and "Unnamed" not in name:
            grid_square_data["sites"].append(site_obj)

    if grid_square_data["sites"]:
        all_results.append(grid_square_data)

# Export the final data

# with open("river_industrial_data.json", "w", encoding="utf-8") as f:
#     json.dump(all_results, f, indent=4, ensure_ascii=False)
#
# render_map(all_results, "pollution_map.html")   # ← add this
# print(f"Data exported. {len(all_results)} squares. Map → pollution_map.html")

with open("river_industrial_data.json", "w", encoding="utf-8") as f:
    json.dump(all_results, f, indent=4, ensure_ascii=False)

print(f"Data exported successfully. Found sites in {len(all_results)} squares.")





# while True:
#     pass
#
#
# fig, ax = plt.subplots(figsize=(10, 8))
#
# grid_size_km = 10.0
# res = grid_size_km / 111.0
# # Draw the squares first (so they are in the background)
# for gx, gy in squares:
#     # Convert index back to coordinates
#     lower_left_lon = gx * res
#     lower_left_lat = gy * res
#
#     # Create a square patch
#     rect = patches.Rectangle(
#         (lower_left_lon, lower_left_lat),
#         res, res,
#         linewidth=0.5,
#         edgecolor='blue',
#         facecolor='cyan',
#         alpha=0.3  # Transparency
#     )
#     ax.add_patch(rect)
#
# # Draw the river line on top
# river_lons = [p[0] for p in abbr_points]
# river_lats = [p[1] for p in abbr_points]
# ax.plot(river_lons, river_lats, color='darkblue', linewidth=1, label="Bregalnica River")
#
# # Formatting
# ax.set_aspect('equal')  # Very important to prevent stretching
# plt.title(f"River Buffer Coverage ({len(squares)} squares)")
# plt.xlabel("Longitude")
# plt.ylabel("Latitude")
# plt.show()
# # print("Skopke")
# # print(json.dumps(data, indent=2))
