import requests
import json


def overpass_query_byName(name):
    return f"""
    [out:json][timeout:25][bbox:40.85,20.45,42.37,23.03];
    // gather results
    nwr["boundary"="administrative"]["name"="{name}"];
    // print results
    out bb;
    """
def overpass_query_byID(id):
    return f"""
        [out:json][timeout:25];
        // Query a relation specifically by its ID
        rel({id});
        // print results (out bb gives you the bounding box)
        out bb;
        """
# 1. Define your query using the custom bbox syntax [s, w, n, e]
# This example looks for factories in a small area of Detroit
overpass_url = "https://overpass.kumi.systems/api/interpreter"
overpass_query_industrial = """
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“(man_made=works or product=* or building=industrial) and type:node”
*/
[out:json][timeout:25][bbox:41.92,21.35,42.05,21.55];
// gather results
(
  node["man_made"="works"]({{bbox}});
  node["product"]({{bbox}});
  node["building"="industrial"]({{bbox}});
);
// print results
out geom;
"""

overpass_query_rivers = """
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“(man_made=works or product=* or building=industrial) and type:node”
*/
[out:json][timeout:25][bbox:41.92,21.35,42.05,21.55];
// gather results
way["waterway"="river"];
// print results
out geom;
"""

overpass_query_vardar="""
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“waterway=river and name=Vardar and type:way”
*/
[out:json][timeout:25];
// gather results
way["waterway"="river"]["name"="Вардар"]({{bbox}});
// print results
out geom;"""

overpass_query_place="""
[out:json][timeout:25];
// 1. Find the area named "Skopje" and store it in a variable called .a
area[name="Скопје"]->.a;

// 2. Use that area as a filter instead of a bbox
(
  nwr["man_made"="works"](area.a);
  way["waterway"="river"](area.a);
);

// 3. Output results
out geom;"""

overpass_query_city_bounds = """
[out:json][timeout:25];
# Find the administrative boundary of Skopje
relation["boundary"="administrative"]["name"="Скопје"];
# 'out bb' is a shortcut that returns just the bounding box of the object
out bb; 
"""
overpass_query_Skopje="""
[out:json][timeout:25][bbox:40.85,20.45,42.37,23.03];
// gather results
nwr["boundary"="administrative"]["name"="Скопје"];
// print results
out bb;
"""


response = requests.post(overpass_url, data={'data': overpass_query_byName("Macedonia")})

#for getting bounds

data = response.json()
print("Skopke")
print(json.dumps(data, indent=2))

if "elements" in data and len(data["elements"]) > 0:
    # Get the bounds dictionary from the first element
    bounds = data["elements"][0].get("bounds")

    if bounds:
        s = bounds['minlat']
        w = bounds['minlon']
        n = bounds['maxlat']
        e = bounds['maxlon']

        print(f"Skopje BBox: {s}, {w}, {n}, {e}")

        # This is now ready to be plugged into your next query
        custom_bbox = f"{s},{w},{n},{e}"

while True:
    pass
# 2. Send the request
response = requests.post(overpass_url, data={'data': overpass_query_place})


data = response.json()
print("Skopke")
#print(json.dumps(data, indent=2))

for element in data['elements']:
    if element['type'] == 'way' and 'bounds' in element:
        b = element['bounds']

        # Access individual values
        s = b['minlat']
        w = b['minlon']
        n = b['maxlat']
        e = b['maxlon']

        tags = element.get("tags", {})
        namem = tags.get("name", "Unnamed")
        print(f"BBox for {element['id']}, {namem}: [{s}, {w}, {n}, {e}]")

        # Format it specifically for a future Overpass Query string
        overpass_bbox = f"{s},{w},{n},{e}"
        print(f"Formatted for Overpass: ({overpass_bbox})")

# 2. Iterate through the elements to find rivers
for element in data.get('elements', []):
    # We only care about 'ways' that have tags
    if element.get('type') == 'way' and 'tags' in element:
        tags = element['tags']

        # Pick the river by name (e.g., 'Маркова Река' or 'Vardar')
        river_name = tags.get('name', 'Unnamed River')

        # If you want to filter for a specific one:

        print(f"--- Iterating through: {river_name} ---")

        # 3. Iterate through the coordinate points in 'geometry'
        # Each point is a dictionary: {'lat': 41.xxx, 'lon': 21.xxx}
        points = element.get('geometry', [])

        for i, point in enumerate(points):
            lat = point['lat']
            lon = point['lon']
            print(f"Point {i}: Lat {lat}, Lon {lon}")

print(json.dumps(data, indent=2))

print(response.json())
# 3. Parse the JSON results
if response.status_code == 200:
    data = response.json()
    print(f"Found {len(data['elements'])} industrial features.")
else:
    print("Error:", response.status_code)

# config = SHConfig()
# # config.client_id = "YOUR_ID"
# # config.client_secret = "YOUR_SECRET"
#
# bbox = BBox([21.4, 41.9, 21.6, 42.1], crs=CRS.WGS84)  # Skopje area
#
# request = SentinelHubRequest(
#     data_folder="data",
#     evalscript="""
#     //VERSION=3
#     return [B04, B03, B02];
#     """,
#     input_data=[
#         SentinelHubRequest.input_data(
#             data_collection=DataCollection.SENTINEL2_L2A,
#             time_interval=("2024-01-01", "2024-01-10")
#         )
#     ],
#     responses=[
#         SentinelHubRequest.output_response("default", "png")
#     ],
#     bbox=bbox,
#     size=(512, 512),
#     config=config
# )
#